/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    tags: Tag;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    branding: Branding;
    homepage: Homepage;
    about: About;
    'services-page': ServicesPage;
    legal: Legal;
    navigation: Navigation;
  };
  globalsSelect: {
    branding: BrandingSelect<false> | BrandingSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  clientName?: string | null;
  clientLocation?: string | null;
  /**
   * e.g. Chiropractic, Acupuncture, Integrative Medicine
   */
  clientPracticeType?: string | null;
  clientServices?: string | null;
  /**
   * e.g. Branding, ecommerce, paid media
   */
  clientEngagementFocus?: string | null;
  /**
   * e.g. Local, Regional, National
   */
  clientMarketReach?: string | null;
  /**
   * Add 3 standard metric cards for the homepage grid. Use Full Width Row only if you want a fourth bar on the blog post page.
   */
  caseStudyMetrics?:
    | {
        eyebrow: string;
        /**
         * Leave empty to use Display Value only (no count-up animation).
         */
        value?: number | null;
        prefix?: string | null;
        suffix?: string | null;
        decimals?: number | null;
        /**
         * Use for values like “Local → National” that should not animate.
         */
        displayValue?: string | null;
        description: string;
        isHighlighted?: boolean | null;
        highlightLabel?: string | null;
        spanFull?: boolean | null;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  category: number | Category;
  tags?: (number | Tag)[] | null;
  /**
   * Choose Case Study to edit animated metrics and use the case study layout.
   */
  postType: 'article' | 'case-study';
  authorName?: string | null;
  /**
   * e.g. "9 min read"
   */
  readTime?: string | null;
  publishedAt: string;
  status: 'draft' | 'published';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  clientName?: T;
  clientLocation?: T;
  clientPracticeType?: T;
  clientServices?: T;
  clientEngagementFocus?: T;
  clientMarketReach?: T;
  caseStudyMetrics?:
    | T
    | {
        eyebrow?: T;
        value?: T;
        prefix?: T;
        suffix?: T;
        decimals?: T;
        displayValue?: T;
        description?: T;
        isHighlighted?: T;
        highlightLabel?: T;
        spanFull?: T;
        id?: T;
      };
  featuredImage?: T;
  category?: T;
  tags?: T;
  postType?: T;
  authorName?: T;
  readTime?: T;
  publishedAt?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  /**
   * Shown in the site header and footer. SVG or PNG recommended. After uploading or choosing a file, click Save.
   */
  logo?: (number | null) | Media;
  logoAlt?: string | null;
  /**
   * Height of the logo in the header and footer. Width scales automatically. Try 40–56 if it looks small.
   */
  logoHeight?: number | null;
  /**
   * Eyebrows, text links, and general brand accents.
   */
  primaryColor?: string | null;
  /**
   * Icons in problem cards, services, and similar UI.
   */
  iconColor?: string | null;
  /**
   * Soft highlights and decorative accent surfaces.
   */
  accentColor?: string | null;
  /**
   * Primary CTA button background.
   */
  buttonColor?: string | null;
  /**
   * Text/icon color on primary buttons.
   */
  buttonTextColor?: string | null;
  /**
   * Border/fill color for outline and secondary buttons.
   */
  secondaryButtonColor?: string | null;
  /**
   * Text color on secondary/outline buttons.
   */
  secondaryButtonTextColor?: string | null;
  /**
   * Main page background color.
   */
  backgroundColor?: string | null;
  /**
   * Secondary surfaces, muted fills, and soft cards.
   */
  secondaryColor?: string | null;
  /**
   * Color for section titles and other headings.
   */
  headingColor?: string | null;
  /**
   * Main paragraph and body copy color.
   */
  textColor?: string | null;
  /**
   * Supporting copy, captions, and nav links.
   */
  mutedTextColor?: string | null;
  /**
   * Dividers, outlines, and card borders.
   */
  borderColor?: string | null;
  /**
   * Keyboard focus outlines on buttons and inputs.
   */
  focusRingColor?: string | null;
  /**
   * Applied to all headings (h1–h6).
   */
  headingFont:
    | 'Satoshi'
    | 'Manrope'
    | 'Space Grotesk'
    | 'Lexend Deca'
    | 'Geist'
    | 'Inter'
    | 'DM Sans'
    | 'Outfit'
    | 'Plus Jakarta Sans'
    | 'Poppins'
    | 'Montserrat'
    | 'Nunito Sans'
    | 'Source Sans 3'
    | 'IBM Plex Sans'
    | 'Lato'
    | 'Open Sans'
    | 'Roboto'
    | 'Playfair Display'
    | 'Fraunces'
    | 'Merriweather'
    | 'Libre Baskerville';
  /**
   * Applied to body copy and UI text.
   */
  bodyFont:
    | 'Satoshi'
    | 'Manrope'
    | 'Space Grotesk'
    | 'Lexend Deca'
    | 'Geist'
    | 'Inter'
    | 'DM Sans'
    | 'Outfit'
    | 'Plus Jakarta Sans'
    | 'Poppins'
    | 'Montserrat'
    | 'Nunito Sans'
    | 'Source Sans 3'
    | 'IBM Plex Sans'
    | 'Lato'
    | 'Open Sans'
    | 'Roboto'
    | 'Playfair Display'
    | 'Fraunces'
    | 'Merriweather'
    | 'Libre Baskerville';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  gsHeroEyebrow?: string | null;
  gsHeroHeadline?: string | null;
  gsHeroHeadlineAccent?: string | null;
  gsHeroSubheadline?: string | null;
  gsHeroPrimaryCta?: string | null;
  gsHeroSecondaryCta?: string | null;
  gsHeroStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  gsWhoEyebrow?: string | null;
  gsWhoHeadline?: string | null;
  gsWhoDescription?: string | null;
  gsWhoCriteria?:
    | {
        icon:
          | 'line-chart'
          | 'trending-down'
          | 'compass'
          | 'bar-chart-3'
          | 'megaphone'
          | 'layout-template'
          | 'users'
          | 'gauge'
          | 'activity'
          | 'bone'
          | 'flask-conical'
          | 'leaf'
          | 'heart-pulse'
          | 'sparkles'
          | 'zap'
          | 'palette'
          | 'database';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  gsWhoDisqualifier?: string | null;
  gsFunnelEyebrow?: string | null;
  gsFunnelHeadline?: string | null;
  gsFunnelDescription?: string | null;
  gsFunnelLinkLabel?: string | null;
  gsFunnelLinkUrl?: string | null;
  gsFunnelSteps?:
    | {
        tag: string;
        title: string;
        detail: string;
        buttonLabel: string;
        image?: (number | null) | Media;
        imageUrl?: string | null;
        imageAlt?: string | null;
        id?: string | null;
      }[]
    | null;
  gsPillarsEyebrow?: string | null;
  gsPillarsHeadline?: string | null;
  gsPillarsDescription?: string | null;
  gsPillars?:
    | {
        icon:
          | 'line-chart'
          | 'trending-down'
          | 'compass'
          | 'bar-chart-3'
          | 'megaphone'
          | 'layout-template'
          | 'users'
          | 'gauge'
          | 'activity'
          | 'bone'
          | 'flask-conical'
          | 'leaf'
          | 'heart-pulse'
          | 'sparkles'
          | 'zap'
          | 'palette'
          | 'database';
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  gsIncludedEyebrow?: string | null;
  gsIncludedHeadline?: string | null;
  gsIncludedDescription?: string | null;
  gsIncludedItems?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  caseStudyEyebrow?: string | null;
  caseStudyHeadline?: string | null;
  /**
   * Choose a published case study post to show in this section.
   */
  caseStudyFeaturedPost?: (number | null) | Post;
  gsResultsEyebrow?: string | null;
  gsResultsHeadline?: string | null;
  /**
   * For your team only — not shown on the live site.
   */
  gsResultsPlaceholder?: string | null;
  gsTestimonials?:
    | {
        photo?: (number | null) | Media;
        photoUrl?: string | null;
        photoAlt?: string | null;
        quote: string;
        name: string;
        practice: string;
        id?: string | null;
      }[]
    | null;
  gsTeamEyebrow?: string | null;
  gsTeamHeadline?: string | null;
  gsTeamDescription?: string | null;
  gsTeamImage?: (number | null) | Media;
  gsTeamImageUrl?: string | null;
  gsTeamImageAlt?: string | null;
  gsTeamMembers?:
    | {
        photo?: (number | null) | Media;
        photoUrl?: string | null;
        photoAlt?: string | null;
        name: string;
        role: string;
        bio: string;
        linkedinUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  gsArticlesEyebrow?: string | null;
  gsArticlesHeadline?: string | null;
  gsArticlesLinkLabel?: string | null;
  gsNextEyebrow?: string | null;
  gsNextHeadline?: string | null;
  gsNextSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  gsAuditHeadline?: string | null;
  gsAuditDescription?: string | null;
  gsAuditButtonLabel?: string | null;
  gsAuditButtonUrl?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroDescription?: string | null;
  heroImage?: (number | null) | Media;
  heroImageAlt?: string | null;
  /**
   * Choose which part of the image stays in frame when it is cropped.
   */
  heroImagePosition?:
    | (
        | 'center'
        | 'top'
        | 'bottom'
        | 'left'
        | 'right'
        | 'top-left'
        | 'top-center'
        | 'top-right'
        | 'center-left'
        | 'center-right'
        | 'bottom-left'
        | 'bottom-center'
        | 'bottom-right'
      )
    | null;
  visionMissionHeadline?: string | null;
  visionLabel?: string | null;
  visionText?: string | null;
  missionLabel?: string | null;
  missionText?: string | null;
  processEyebrow?: string | null;
  processTitle?: string | null;
  processDescription?: string | null;
  processCenterTitle?: string | null;
  processCenterSubtitle?: string | null;
  processItems?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  teamEyebrow?: string | null;
  teamTitle?: string | null;
  teamDescription?: string | null;
  teamMembers?:
    | {
        name: string;
        role: string;
        bio: string;
        photo?: (number | null) | Media;
        /**
         * Choose which part of the image stays in frame when it is cropped.
         */
        photoPosition?:
          | (
              | 'center'
              | 'top'
              | 'bottom'
              | 'left'
              | 'right'
              | 'top-left'
              | 'top-center'
              | 'top-right'
              | 'center-left'
              | 'center-right'
              | 'bottom-left'
              | 'bottom-center'
              | 'bottom-right'
            )
          | null;
        /**
         * Shown when no photo is uploaded, e.g. AB
         */
        initials?: string | null;
        /**
         * Full profile URL, e.g. https://linkedin.com/in/username
         */
        linkedinUrl?: string | null;
        /**
         * Channel or profile URL
         */
        youtubeUrl?: string | null;
        /**
         * Profile URL
         */
        instagramUrl?: string | null;
        /**
         * Profile URL
         */
        xUrl?: string | null;
        /**
         * Page or profile URL
         */
        facebookUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  caseStudyEyebrow?: string | null;
  caseStudyHeadline?: string | null;
  /**
   * Choose a published case study post to show in this section.
   */
  caseStudyFeaturedPost?: (number | null) | Post;
  ctaHeadline?: string | null;
  ctaDescription?: string | null;
  ctaButton?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroDescription?: string | null;
  offeringsEyebrow?: string | null;
  offeringsHeadline?: string | null;
  offeringsItems?:
    | {
        icon:
          | 'line-chart'
          | 'trending-down'
          | 'compass'
          | 'bar-chart-3'
          | 'megaphone'
          | 'layout-template'
          | 'users'
          | 'gauge'
          | 'activity'
          | 'bone'
          | 'flask-conical'
          | 'leaf'
          | 'heart-pulse'
          | 'sparkles'
          | 'zap'
          | 'palette'
          | 'database';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  aboutEyebrow?: string | null;
  aboutHeadline?: string | null;
  aboutDescription?: string | null;
  aboutCta?: string | null;
  aboutImage?: (number | null) | Media;
  aboutImageAlt?: string | null;
  caseStudyEyebrow?: string | null;
  caseStudyHeadline?: string | null;
  /**
   * Choose a published case study post to show in this section.
   */
  caseStudyFeaturedPost?: (number | null) | Post;
  ctaHeadline?: string | null;
  ctaSubheadline?: string | null;
  ctaButton?: string | null;
  technologyEyebrow?: string | null;
  technologyHeadline?: string | null;
  technologyDescription?: string | null;
  /**
   * Each card shows a platform image, title, and list of tools.
   */
  technologyCategories?:
    | {
        image?: (number | null) | Media;
        imageAlt: string;
        title: string;
        items?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  privacyEyebrow?: string | null;
  privacyTitle: string;
  privacyLastUpdated?: string | null;
  privacyIntro?: string | null;
  privacySections?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  privacySeoTitle?: string | null;
  privacySeoDescription?: string | null;
  termsEyebrow?: string | null;
  termsTitle: string;
  termsLastUpdated?: string | null;
  termsIntro?: string | null;
  termsSections?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  termsSeoTitle?: string | null;
  termsSeoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerNavItems?:
    | {
        label: string;
        /**
         * Internal path (e.g. /about) or full URL.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  headerCtaLabel?: string | null;
  headerCtaHref?: string | null;
  footerNavItems?:
    | {
        label: string;
        /**
         * Internal path (e.g. /about) or full URL.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  logo?: T;
  logoAlt?: T;
  logoHeight?: T;
  primaryColor?: T;
  iconColor?: T;
  accentColor?: T;
  buttonColor?: T;
  buttonTextColor?: T;
  secondaryButtonColor?: T;
  secondaryButtonTextColor?: T;
  backgroundColor?: T;
  secondaryColor?: T;
  headingColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  borderColor?: T;
  focusRingColor?: T;
  headingFont?: T;
  bodyFont?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  gsHeroEyebrow?: T;
  gsHeroHeadline?: T;
  gsHeroHeadlineAccent?: T;
  gsHeroSubheadline?: T;
  gsHeroPrimaryCta?: T;
  gsHeroSecondaryCta?: T;
  gsHeroStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  gsWhoEyebrow?: T;
  gsWhoHeadline?: T;
  gsWhoDescription?: T;
  gsWhoCriteria?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  gsWhoDisqualifier?: T;
  gsFunnelEyebrow?: T;
  gsFunnelHeadline?: T;
  gsFunnelDescription?: T;
  gsFunnelLinkLabel?: T;
  gsFunnelLinkUrl?: T;
  gsFunnelSteps?:
    | T
    | {
        tag?: T;
        title?: T;
        detail?: T;
        buttonLabel?: T;
        image?: T;
        imageUrl?: T;
        imageAlt?: T;
        id?: T;
      };
  gsPillarsEyebrow?: T;
  gsPillarsHeadline?: T;
  gsPillarsDescription?: T;
  gsPillars?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  gsIncludedEyebrow?: T;
  gsIncludedHeadline?: T;
  gsIncludedDescription?: T;
  gsIncludedItems?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  caseStudyEyebrow?: T;
  caseStudyHeadline?: T;
  caseStudyFeaturedPost?: T;
  gsResultsEyebrow?: T;
  gsResultsHeadline?: T;
  gsResultsPlaceholder?: T;
  gsTestimonials?:
    | T
    | {
        photo?: T;
        photoUrl?: T;
        photoAlt?: T;
        quote?: T;
        name?: T;
        practice?: T;
        id?: T;
      };
  gsTeamEyebrow?: T;
  gsTeamHeadline?: T;
  gsTeamDescription?: T;
  gsTeamImage?: T;
  gsTeamImageUrl?: T;
  gsTeamImageAlt?: T;
  gsTeamMembers?:
    | T
    | {
        photo?: T;
        photoUrl?: T;
        photoAlt?: T;
        name?: T;
        role?: T;
        bio?: T;
        linkedinUrl?: T;
        id?: T;
      };
  gsArticlesEyebrow?: T;
  gsArticlesHeadline?: T;
  gsArticlesLinkLabel?: T;
  gsNextEyebrow?: T;
  gsNextHeadline?: T;
  gsNextSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  gsAuditHeadline?: T;
  gsAuditDescription?: T;
  gsAuditButtonLabel?: T;
  gsAuditButtonUrl?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroImage?: T;
  heroImageAlt?: T;
  heroImagePosition?: T;
  visionMissionHeadline?: T;
  visionLabel?: T;
  visionText?: T;
  missionLabel?: T;
  missionText?: T;
  processEyebrow?: T;
  processTitle?: T;
  processDescription?: T;
  processCenterTitle?: T;
  processCenterSubtitle?: T;
  processItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  teamEyebrow?: T;
  teamTitle?: T;
  teamDescription?: T;
  teamMembers?:
    | T
    | {
        name?: T;
        role?: T;
        bio?: T;
        photo?: T;
        photoPosition?: T;
        initials?: T;
        linkedinUrl?: T;
        youtubeUrl?: T;
        instagramUrl?: T;
        xUrl?: T;
        facebookUrl?: T;
        id?: T;
      };
  caseStudyEyebrow?: T;
  caseStudyHeadline?: T;
  caseStudyFeaturedPost?: T;
  ctaHeadline?: T;
  ctaDescription?: T;
  ctaButton?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroDescription?: T;
  offeringsEyebrow?: T;
  offeringsHeadline?: T;
  offeringsItems?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  aboutEyebrow?: T;
  aboutHeadline?: T;
  aboutDescription?: T;
  aboutCta?: T;
  aboutImage?: T;
  aboutImageAlt?: T;
  caseStudyEyebrow?: T;
  caseStudyHeadline?: T;
  caseStudyFeaturedPost?: T;
  ctaHeadline?: T;
  ctaSubheadline?: T;
  ctaButton?: T;
  technologyEyebrow?: T;
  technologyHeadline?: T;
  technologyDescription?: T;
  technologyCategories?:
    | T
    | {
        image?: T;
        imageAlt?: T;
        title?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  privacyEyebrow?: T;
  privacyTitle?: T;
  privacyLastUpdated?: T;
  privacyIntro?: T;
  privacySections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  privacySeoTitle?: T;
  privacySeoDescription?: T;
  termsEyebrow?: T;
  termsTitle?: T;
  termsLastUpdated?: T;
  termsIntro?: T;
  termsSections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  termsSeoTitle?: T;
  termsSeoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerNavItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCtaLabel?: T;
  headerCtaHref?: T;
  footerNavItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PatientJourneyBlock".
 */
export interface PatientJourneyBlock {
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  steps?:
    | {
        label: string;
        teaser: string;
        badTitle?: string | null;
        badDescription: string;
        goodTitle: string;
        goodDescription: string;
        insight: string;
        id?: string | null;
      }[]
    | null;
  completionTitle?: string | null;
  completionDescription?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'patientJourney';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BudgetPlannerBlock".
 */
export interface BudgetPlannerBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'budgetPlanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferBuilderBlock".
 */
export interface OfferBuilderBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'offerBuilder';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogCalloutBlock".
 */
export interface BlogCalloutBlock {
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogCallout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogCardGridBlock".
 */
export interface BlogCardGridBlock {
  cards?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogCardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogTagPillsBlock".
 */
export interface BlogTagPillsBlock {
  pills?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogTagPills';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogBulletListBlock".
 */
export interface BlogBulletListBlock {
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogBulletList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogReferencesBlock".
 */
export interface BlogReferencesBlock {
  label?: string | null;
  items?:
    | {
        text: string;
        /**
         * Optional. If set, the link label below becomes clickable.
         */
        url?: string | null;
        linkLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogReferences';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogAuthorBioBlock".
 */
export interface BlogAuthorBioBlock {
  photo?: (number | null) | Media;
  name: string;
  role?: string | null;
  bio: string;
  linkedinUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogAuthorBio';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogArticleCtaBlock".
 */
export interface BlogArticleCtaBlock {
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogArticleCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}