import type { GrowthAssessmentContent } from "@/lib/growth-assessment-defaults"

export function growthAssessmentToPayloadData(content: GrowthAssessmentContent) {
  return {
    heroEyebrow: content.heroEyebrow,
    heroHeadline: content.heroHeadline,
    heroDescription: content.heroDescription,
    heroPrimaryCta: content.heroPrimaryCta,
    heroSecondaryCta: content.heroSecondaryCta,
    heroNote: content.heroNote,
    heroSamplePractice: content.heroSamplePractice,
    heroSampleScore: content.heroSampleScore,
    heroTopOpportunity: content.heroTopOpportunity,
    heroSuggestedRange: content.heroSuggestedRange,
    heroPriorityActions: content.heroPriorityActions.map((label) => ({ label })),
    problemEyebrow: content.problemEyebrow,
    problemHeadline: content.problemHeadline,
    problemDescription: content.problemDescription,
    problemStages: content.problemStages.map((label) => ({ label })),
    problemHighlightStage: content.problemHighlightStage,
    problemFootnote: content.problemFootnote,
    assessEyebrow: content.assessEyebrow,
    assessHeadline: content.assessHeadline,
    assessDescription: content.assessDescription,
    assessItems: content.assessItems,
    dataEyebrow: content.dataEyebrow,
    dataHeadline: content.dataHeadline,
    dataDescription: content.dataDescription,
    dataCredibilityLine: content.dataCredibilityLine,
    dataSources: content.dataSources,
    dataHumanReviewLabel: content.dataHumanReviewLabel,
    dataFlowSteps: content.dataFlowSteps.map((label) => ({ label })),
    dataSourcesNote: content.dataSourcesNote,
    useCasesHeadline: content.useCasesHeadline,
    useCasesDescription: content.useCasesDescription,
    useCases: content.useCases,
    dataBridgeLine: content.dataBridgeLine,
    howEyebrow: content.howEyebrow,
    howHeadline: content.howHeadline,
    howSteps: content.howSteps,
    howNote: content.howNote,
    reportEyebrow: content.reportEyebrow,
    reportHeadline: content.reportHeadline,
    reportDescription: content.reportDescription,
    reportChecklist: content.reportChecklist.map((label) => ({ label })),
    reportSamplePlanLabel: content.reportSamplePlanLabel,
    reportSamplePlanUrl: content.reportSamplePlanUrl,
    financialEyebrow: content.financialEyebrow,
    financialHeadline: content.financialHeadline,
    financialDescription: content.financialDescription,
    financialDisclaimer: content.financialDisclaimer,
    financialScenarios: content.financialScenarios.map((scenario) => ({
      title: scenario.title,
      description: scenario.description,
      featured: scenario.featured ?? false,
      rows: scenario.rows,
    })),
    whoEyebrow: content.whoEyebrow,
    whoHeadline: content.whoHeadline,
    whoFitItems: content.whoFitItems.map((label) => ({ label })),
    whoNotFitItems: content.whoNotFitItems.map((label) => ({ label })),
    whoNotFitNote: content.whoNotFitNote,
    whyEyebrow: content.whyEyebrow,
    whyHeadline: content.whyHeadline,
    whyDescription: content.whyDescription,
    whyItems: content.whyItems.map((label) => ({ label })),
    findingsEyebrow: content.findingsEyebrow,
    findingsHeadline: content.findingsHeadline,
    findingsItems: content.findingsItems,
    faqEyebrow: content.faqEyebrow,
    faqHeadline: content.faqHeadline,
    faqItems: content.faqItems,
    practitionersEyebrow: content.practitionersEyebrow,
    practitionersHeadline: content.practitionersHeadline,
    practitionersDescription: content.practitionersDescription,
    practitioners: content.practitioners.map((practitioner) => ({
      name: practitioner.name,
      specialty: practitioner.specialty,
      quote: practitioner.quote,
      initials: practitioner.initials ?? "",
      caseStudyUrl: practitioner.caseStudyUrl ?? "",
      caseStudyLabel: practitioner.caseStudyLabel ?? "",
    })),
    formEyebrow: content.formEyebrow,
    formHeadline: content.formHeadline,
    formDescription: content.formDescription,
    formBullets: content.formBullets.map((label) => ({ label })),
    formQuote: content.formQuote,
    formCtaLabel: content.formCtaLabel,
    sectionCtaLabel: content.sectionCtaLabel,
    formShowInvestmentStep: content.formShowInvestmentStep,
    formInvestmentOptions: content.formInvestmentOptions.map((label) => ({ label })),
    formProcessingSteps: content.formProcessingSteps.map((label) => ({ label })),
    seoTitle: content.seoTitle,
    seoDescription: content.seoDescription,
  }
}
