import type { GrowthSystemContent } from "@/lib/homepage-template"

export function growthSystemToPayloadData(content: GrowthSystemContent) {
  return {
    gsHeroEyebrow: content.heroEyebrow,
    gsHeroHeadline: content.heroHeadline,
    gsHeroHeadlineAccent: content.heroHeadlineAccent,
    gsHeroSubheadline: content.heroSubheadline,
    gsHeroPrimaryCta: content.heroPrimaryCta,
    gsHeroSecondaryCta: content.heroSecondaryCta,
    gsHeroStats: content.heroStats,
    gsWhoEyebrow: content.whoEyebrow,
    gsWhoHeadline: content.whoHeadline,
    gsWhoDescription: content.whoDescription,
    gsWhoCriteria: content.whoCriteria,
    gsWhoDisqualifier: content.whoDisqualifier,
    gsFunnelEyebrow: content.funnelEyebrow,
    gsFunnelHeadline: content.funnelHeadline,
    gsFunnelDescription: content.funnelDescription,
    gsFunnelLinkLabel: content.funnelLinkLabel,
    gsFunnelLinkUrl: content.funnelLinkUrl,
    gsFunnelSteps: content.funnelSteps,
    gsPillarsEyebrow: content.pillarsEyebrow,
    gsPillarsHeadline: content.pillarsHeadline,
    gsPillarsDescription: content.pillarsDescription,
    gsPillars: content.pillars,
    gsIncludedEyebrow: content.includedEyebrow,
    gsIncludedHeadline: content.includedHeadline,
    gsIncludedDescription: content.includedDescription,
    gsIncludedItems: content.includedItems,
    caseStudyEyebrow: content.caseStudyHighlight.eyebrow,
    caseStudyHeadline: content.caseStudyHighlight.headline,
    gsResultsEyebrow: content.resultsEyebrow,
    gsResultsHeadline: content.resultsHeadline,
    gsResultsPlaceholder: content.resultsPlaceholder,
    gsTestimonials: content.testimonials,
    gsTeamEyebrow: content.teamEyebrow,
    gsTeamHeadline: content.teamHeadline,
    gsTeamDescription: content.teamDescription,
    gsTeamImageUrl: content.teamImageUrl,
    gsTeamImageAlt: content.teamImageAlt,
    gsTeamMembers: content.teamMembers,
    gsArticlesEyebrow: content.articlesEyebrow,
    gsArticlesHeadline: content.articlesHeadline,
    gsArticlesLinkLabel: content.articlesLinkLabel,
    gsNextEyebrow: content.nextEyebrow,
    gsNextHeadline: content.nextHeadline,
    gsNextSteps: content.nextSteps,
    gsAuditHeadline: content.auditHeadline,
    gsAuditDescription: content.auditDescription,
    gsAuditButtonLabel: content.auditButtonLabel,
    gsAuditButtonUrl: content.auditButtonUrl,
  }
}
